### ISSUE TITLE
Remove optimization from README

### ISSUE THREAD

**Issue by vurvdev** [TheXYZNetwork/SIMPSit#5]
Hope this reaches you well,

After briefly checking the code, I don't really see much focus on optimization as promised on the README, so I think it'd be best to remove it.

```diff
-A rewrite of the sit anywhere script. Designed for servers, with optimization and simplicity in mind.
+A rewrite of the sit anywhere script. Designed for servers with simplicity in mind.
```

I have included a diff to follow for changing the README file.

Cheers

**Comment by 0wain** [comment]
Hi,

Thanks for reaching out.

What do you find to be unoptimised? 

In comparison to the original sit anywhere script (Which is where this optimisation benchmark is set), this vastly outperforms.

**Comment by vurvdev** [comment]
Hello,

Thank you for your quick response! I now understand you meant optimized in relation to the original script, maybe this could be made more clear on the README as it already proven confusing to me here?

I have also included a list of points I found to be unoptimized below:

https://github.com/TheXYZNetwork/SIMPSit/blob/c8848792f7c947b46c97502a0b561a23419467e9/lua/simp_sit/core/cl_core.lua#L2 ( runtime singleplayer check ☹️ )

https://github.com/TheXYZNetwork/SIMPSit/blob/c8848792f7c947b46c97502a0b561a23419467e9/lua/simp_sit/core/cl_core.lua#L6 ( not using lookup table 😭 )

https://github.com/TheXYZNetwork/SIMPSit/blob/c8848792f7c947b46c97502a0b561a23419467e9/lua/simp_sit/core/sv_core.lua#L116 ( world would not be valid ☹️. looking at your other logic that calls this function, I don't think ent could be nil either. )

https://github.com/TheXYZNetwork/SIMPSit/blob/c8848792f7c947b46c97502a0b561a23419467e9/lua/simp_sit/core/sv_core.lua#L74 ( disttosqr? ☹️ )

https://github.com/TheXYZNetwork/SIMPSit/blob/c8848792f7c947b46c97502a0b561a23419467e9/lua/simp_sit/core/sv_core.lua#L63 ( quicktrace is not actually quick ☹️ )

https://github.com/TheXYZNetwork/SIMPSit/blob/c8848792f7c947b46c97502a0b561a23419467e9/lua/simp_sit/core/sv_core.lua#L167 ( runtime angle constructor 😢 )

https://github.com/TheXYZNetwork/SIMPSit/blob/c8848792f7c947b46c97502a0b561a23419467e9/lua/simp_sit/core/sv_core.lua#L172 ( can vehicle be nil here ❓ )

https://github.com/TheXYZNetwork/SIMPSit/blob/c8848792f7c947b46c97502a0b561a23419467e9/lua/simp_sit/core/sv_core.lua#L196 ( can tUndo.Name be anything but a string here ❓ )

Additionally your use of globals and runtime namespacing `X.Y.Z` may incur performance hits. This also combines with your runtime checks for your debug code.

This is not related to optimization, but the structure of the code is also concerning for your point on simplicity -- I find the autorun file overengineered and could be deduplicated, or better yet just unrolled into simple `AddCSLuaFile` and `include` calls. Likely this is also meant to be in comparison to the original addon, however I could see vast improvements here.

Cheers 🙏

**Comment by 0wain** [comment]
Hey,

Thanks for getting back to me.

This is an open source project with Pull Requests enabled. If you would like to contribute improvements, you're welcome to open one.

Thanks again.

**Comment by yogwoggf** [comment]
> Hey,
> 
> Thanks for getting back to me.
> 
> This is an open source project with Pull Requests enabled. If you would like to contribute improvements, you're welcome to open one.
> 
> Thanks again.

This feels overly dismissive and passive-aggressive, not one of his points were addressed. Resorting to "just PR it yourself" isn't exactly a message which would resonate with your optimization ideology which is described in the README and description of this repo.

**Comment by FelixKLG** [comment]
> > Hey,
> > Thanks for getting back to me.
> > This is an open source project with Pull Requests enabled. If you would like to contribute improvements, you're welcome to open one.
> > Thanks again.
> 
> This feels overly dismissive and passive-aggressive, not one of his points were addressed. Resorting to "just PR it yourself" isn't exactly a message which would resonate with your optimization ideology which is described in the README and description of this repo.

Ngl bro, cope. Owain got a job and a life, he's not withering away wasting his life playing shitty gmod. 💀
It's open source for a reason, PR it yourself or get over it.

**Comment by vurvdev** [comment]
For that reason, there's no need to be hostile and throw out insults. Leave it as is. He's perfectly at liberty to not make any changes as people are at liberty to raise concerns.

Hope everyone is having a great day 🙏

**Comment by yogwoggf** [comment]
> > > Hey,
> > > Thanks for getting back to me.
> > > This is an open source project with Pull Requests enabled. If you would like to contribute improvements, you're welcome to open one.
> > > Thanks again.
> > 
> > 
> > This feels overly dismissive and passive-aggressive, not one of his points were addressed. Resorting to "just PR it yourself" isn't exactly a message which would resonate with your optimization ideology which is described in the README and description of this repo.
> 
> Ngl bro, cope. Owain got a job and a life, he's not withering away wasting his life playing shitty gmod. 💀 It's open source for a reason, PR it yourself or get over it.

There's an expectation of some level of work involved in maintaining an open-source repository, especially one which encourages contribution such as this one. (PS, the author can archive the repo or transfer ownership if he no longer wants to work on this) Also, there's no reason to be so aggressive as all I was doing was attempting to shed light on what I thought to be an unfair dismissal of a highly beneficial issue report. What could have been done instead was the author of this repo converting the optimizations pointed out into issues that could then have PRs submitted to close them. Instead, the author brashly marked the issue as "completed" (when it was not) and left a highly inconclusive message as the reason for closure.

Considering all of that, there's no denying that the author was being unreasonably rude.

**Comment by FelixKLG** [comment]
> > > > Hey,
> > > > Thanks for getting back to me.
> > > > This is an open source project with Pull Requests enabled. If you would like to contribute improvements, you're welcome to open one.
> > > > Thanks again.
> > > 
> > > 
> > > This feels overly dismissive and passive-aggressive, not one of his points were addressed. Resorting to "just PR it yourself" isn't exactly a message which would resonate with your optimization ideology which is described in the README and description of this repo.
> > 
> > 
> > Ngl bro, cope. Owain got a job and a life, he's not withering away wasting his life playing shitty gmod. 💀 It's open source for a reason, PR it yourself or get over it.
> 
> There's an expectation of some level of work involved in maintaining an open-source repository, especially one which encourages contribution such as this one. (PS, the author can archive the repo or transfer ownership if he no longer wants to work on this) Also, there's no reason to be so aggressive as all I was doing was attempting to shed light on what I thought to be an unfair dismissal of a highly beneficial issue report. What could have been done instead was the author of this repo converting the optimizations pointed out into issues that could then have PRs submitted to close them. Instead, the author brashly marked the issue as "completed" (when it was not) and left a highly inconclusive message as the reason for closure.
> 
> Considering all of that, there's no denying that the author was being unreasonably rude.

fuck off autismoid

**Comment by 0wain** [comment]
Hey all,

Just locking this thread because at the end of the day this is an entirly free project that has no strings attached. If you're not happy with the level of optimisations, then you can simply not use the script. It makes literally no difference to me or my life if you choose to do so, and I think we all could find greater value in our time not arguing over a meaningless thing like a gmod addon.

Some of Vurv's points are valid. The use of `:Distance` over `:DistToSqr`, along with some runtime functions that could be cached (The singleplayer check and the angle). But I also disagree with a couple of notes. For example I think that the `table.HasValue` gives a better configuration experience for less knowledgeable server owners, at the expense of a single tiny forloop. Along with some additional validate checks that are actually relevant (The tUndo.name string check is actually needed, based on a [previous PR made](https://github.com/TheXYZNetwork/SIMPSit/pull/4)). I don't think anything here is a big deal, you're looking at micro-optimizations that (considering these functions run once every few minutes) are going to see meaningless gains.

I have also used that autorun loader script in pretty much every gmod addon I have ever made, and I have easily made [over 200 addons](https://github.com/TheXYZNetwork/PoliceRP-OpenSource/tree/master/addons). Considering it only runs at instance start, I think it's fine.

I don't play gmod anymore. Buy I try to continue to maintain all the open source projects we've published, which you can see by the PRs in any of our top repos. But at the end of the day, you're getting this stuff for free. If Vurv is not interested in opening a PR with these changes, then someone else is welcome to.

Thanks guys.
